# This workflow will do a clean install of node dependencies using Bun, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: GitHub Pages deploy

on:
  push:
    branches: [main]

jobs:
  build:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v4.1.3

      - name: Setup bun üõ†Ô∏è
        uses: oven-sh/setup-bun@v2

      - name: Installing my packages üì¶
        run: bun install

      - name: Build üèóÔ∏è
        run: bun run build
        env:
          NEXT_PUBLIC_MICROSOFT_CLARITY_KEY: ${{ secrets.NEXT_PUBLIC_MICROSOFT_CLARITY_KEY }}
          NEXT_PUBLIC_MICROSOFT_CLARITY_ENABLED: ${{ secrets.NEXT_PUBLIC_MICROSOFT_CLARITY_ENABLED }}
          NEXT_PUBLIC_AMPLITUDE_KEY: ${{ secrets.NEXT_PUBLIC_AMPLITUDE_KEY }}
          NEXT_PUBLIC_AMPLITUDE_ENABLED: ${{ secrets.NEXT_PUBLIC_AMPLITUDE_ENABLED }}

      - name: Deploy üöÄ
        uses: JamesIves/github-pages-deploy-action@v4.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: .
